### ISSUE TITLE
Rename p4_constraints to src?

### ISSUE THREAD

**Issue by stefanheule** [p4lang/p4-constraints#8]
Sorry I only just noticed this, but it seems weird to have a folder called p4_constraints in this repo. Most people seem to call this src, e.g. https://github.com/grpc/grpc. Should we rename it?

**Comment by smolkaj** [comment]
This is a byproduct of the fact that we use Bazel. C/C++ #include paths (both in our project and in other projects depending on p4-constraints) are relative to the root of the project, since this is where the WORKSPACE file sits. So we would end up with awkward include paths if we were to use a `src` folder:
```C
#include "src/frontend/parser.h" 
```
Especially for other projects depending on us,
```C
#include "p4_constraints/frontend/parser.h" 
```
seems more desirable. Note that I choose the folder named to match the namespace name.

The same convention is used by other Bazel projects as well, for example https://github.com/tensorflow/tensorflow, https://github.com/google/iree, ...

**Comment by smolkaj** [comment]
Aother example: https://github.com/abseil/abseil-cpp

**Comment by stefanheule** [comment]
Got it, thanks for the explanation.
